### ISSUE TITLE
How do I trim OPNA VGM that uses ADPCM?

### ISSUE THREAD

**Issue by denjhang** [vgmrips/vgmtools#12]
Currently I know how to trim OPL4 VGM, but I trim OPNA in the same way, and all ADPCM samples are lost.
[sor05_optimized_optimized.zip](https://github.com/vgmrips/vgmtools/files/6326107/sor05_optimized_optimized.zip)

**Comment by ValleyBell** [comment]
simple - do not run vgm_cmp *before* trimming.
Do all trimming on the raw, logged VGMs and run vgm_cmp last. (preferably after all other optimizations)

Due to the lossy optimization that vgm_cmp performs, trimming and especially looping optimized VGMs is many times harder and requires a lot more careful trimming than operating on the raw logged VGMs.

**Comment by superctr** [comment]
Also, this is an issue tracker, not a forum for general questions. Take your questions to the [forum thread](https://vgmrips.net/forum/viewtopic.php?f=3&t=207) instead.

**Comment by denjhang** [comment]
Thanks for answering. I have learned a lot of VGM optimization techniques.
