### ISSUE TITLE
How to scale playback speed

### ISSUE THREAD

**Issue by meyertime** [vgmrips/vgmtools#21]
Hi, @ValleyBell.  Sorry this isn't really an issue as much as it is a question, and I haven't been able to find another way to contact you.  You've been super helpful and responsive!  Thanks for all your work!

So the last issue I'm dealing with in my project is that the `.vgm` files play at about 98% of the speed of the real song in the real game when played using a VGM player ROM in a real Sega Genesis.  Interestingly, it plays at the correct speed when I load the same ROM into a Genesis emulator, so it is something peculiar to the actual hardware and probably the VGM player's programming.  That's really not an issue with `vgmtools`, but it may be something that `vgmtools` can help me work around.

What changes would need to be made to a `.vgm` file to scale its playback speed by about 2%?  I'm aware of the rate setting in the `.vgm` header, but it goes by video frame rate (60 Hz), so it probably won't give me the precision I'm looking for.  I understand that the `.vgm` format assumes a sampling rate of 44100 Hz for the purpose of timing things.  In theory, I could scale the delay values accordingly to produce a tempo change.  But I'm not yet familiar with how the DAC is handled and how to scale that playback as well.

Some other observations:

- The tempo is different, but the pitch of the instruments is the same, so it's mainly just a tempo change that I need.
- The PCM samples appear to play at a correspondingly different pitch, however.  So whatever is affecting the tempo of the song is also affecting the speed that the PCM samples are played.

How can I scale the DAC playback?  Is there anything else that would need to be scaled?  Where would be a good place to integrate this feature into `vgmtools`?  Any tips you could offer would be greatly appreciated.  Thanks!

**Comment by ValleyBell** [comment]
Hi, I'm in the vgmrips IRC channel (irc://irc.digibase.ca/vgmrips) most of the time.

Regarding VGM tempo:
- The VGM "frame rate" header value was invented for games that play at different speeds in NTSC and PAL regions.  
  The basic concept is, that you set it to the Hz of the recording (e.g. 60 Hz) in the VGM and the user can ask the VGM player to play it back at a different speed (e.g 50 Hz) to match the local region.
  The time scaling is implemented on the player side.
- A "tempo scale" tool would probably end up as a separate tool.
- In order to change the tempo of a VGM file, you will have to recalculate *all* delay values that the VGM contains.
  This means commands `61`, `62`, `63`, `70..7F` and `80..8F`.
  (And of course you need to fix the "total samples" and "loop samples" values in the VGM header.)
- Playing back PCM samples on the YM2612 is done by sending the value of each sample of the waveform at a specific time. (i.e. software streaming)
  e.g. DAC value = 0x80, wait 3/44100 s, DAC value = 0x85, wait 3/44100 s, DAC value = 0x88, wait 3/44100 s, DAC value = 0x8A, etc.
  The amount of waiting time between each sample determines the PCM sample pitch.
  This sequence can be done either using sequences of `52 2A ##` (set YM2612 DAC value to ##) + `7#` (wait #+1 samples) - or using the `8#` command (read value from PCM database, set YM2612 DAC to that value, then wait # samples)

**Comment by meyertime** [comment]
Thanks, super helpful as always!  I got this working and put together a draft pull request.

**Comment by meyertime** [comment]
So, I really should read _**all**_ the documentation...  On the [Sega MegaDrive Vgm Player](http://mjsstuf.x10host.com/pages/vgmPlay/vgmPlay.htm) page, it says:

>   Suplied custom version with playback rate scaling,
>   by default the playback speed is slightly wrong (less than 1%)

Sure enough, there is a `Playback delay scale` option.  It works the opposite from the `-ScaleTempo` command that I developed.  Less than 1 makes it faster, more than 1 makes it slower, because it's the delay scale, not the tempo scale.  But it works for my purposes and does the same thing.  Going to close this issue and the pull request.  It will be there if anyone needs it for some other reason and wants to pick it up.
