### ISSUE TITLE
Possible issue with vgm_sro?

### ISSUE THREAD

**Issue by b0x-Cub3d** [vgmrips/vgmtools#23]
I was using vgm_sro for Metamorphic Force (2xK054539) and OutRunners (MultiPCM).

With MF, tracks 14 & 30 seems to display this message for creating the mask
![MF_vgmsro](https://user-images.githubusercontent.com/84808824/163688044-94fad91c-c771-4634-a532-8f2ff613c9e9.png)

The optimized vgm plays fine, but I wonder if there is any inherent issue that might show itself in the future if left unchecked.
[issue with vgm_sro.zip](https://github.com/vgmrips/vgmtools/files/8500483/issue.with.vgm_sro.zip)

With OutRunners, the mask is incorrect thus the music is corrupted. I even tried the one that fixed the MultiPCM vgms back in 2015.

**Comment by ValleyBell** [comment]
The OutRunners / MultiPCM issue was fixed with 9110d93ebd4ee07e677d61f5296162150892fa10.

The case with "Metamorphic Force" is a weird one ... the messages apparently originate from the sound driver reading outside its sample table and thus loading bad data to the chip.
This results in a few spots where the sample type is set to an invalid value (results in silence in MAME) and other spots where samples are played back in reverse.
vgm_sro should eventually support the latter, but I'd like to wait until I have an actual valid test case.
