### ISSUE TITLE
vgm_trim: Unable to set not to trim Loop Sample and End Sample

### ISSUE THREAD

**Issue by denjhang** [vgmrips/vgmtools#33]
![sshot-20240730-175721](https://github.com/user-attachments/assets/b5196ed0-bb9a-42ce-8786-4510a4464b27)

**Comment by denjhang** [comment]
`vgm_trim.exe Thunderdome.vgm 20204 -2 0`

**Comment by ValleyBell** [comment]
End sample 0 is not a valid value.  
see README

**Comment by vampirefrog** [comment]
I can kind of agree with the reporter that the command line arguments could be processed in a slightly more intuitive way, allow me to make a proposal.

- Use option arguments instead of numeric arguments
- Add the arguments --start, --end, --loop, all optional
- Have short versions -s -e -l
- When --start is missing, trim from sample 0
- When --end is missing, trim to last sample
- Issue a warning when there is nothing to be done, because neither --start, --end nor --loop were provided.
