### ISSUE TITLE
Software license?

### ISSUE THREAD

**Issue by jpcima** [vgmrips/vgmtools#6]
Hi, the software license is not indicated in the source.
I found chiptext.c to be a remarkably helpful debugging tool, and I would like to use it in other software, if vgmtools has a license which permits it.

**Comment by felipesanches** [comment]
I am not sure, but **maybe** this is the same problem as discussed at https://github.com/vgmrips/vgmplay/issues/47

**Comment by superctr** [comment]
vgmtools do not contain any emulation code from vgmplay, so it should be encumbered by other licenses. Though chip_cmp, chip_sro etc are to some extent based on the emulators as some state must be emulated in order to optimize VGMs. I'll leave it to @ValleyBell for the final verdict, but as far as I'm concerned, you're free to use my code in this repo for any purpose you want.

**Comment by ValleyBell** [comment]
If we're very strict, then I guess one could say that chip_cmp/chip_srom/chiptext is based off MAME code, as it borrows comments for switch/case blocks and names for constants/member variables from MAME's sound cores.
The actual logic is mostly my own code though.

In any case, feel free to use the code. I don't have any objections.

**Comment by jpcima** [comment]
Thanks, really appreciate it, but just a thing: can this source be attributed a license, like MIT or such?
I think a license can be indicated by comments at top of individual files, like in MAME.

It's desirable that I can precisely identify a license for my sources, particularly because debian has an extremely rigorous process when it comes to this.

**Comment by ValleyBell** [comment]
Here we go ...  
fixed by 1903158cd59dbc034166be224ef24b823bb43201
